<?php
// phpcs:ignoreFile

// Password constants added in PHP 7.2 & 7.3

const PASSWORD_ARGON2I = 2;
const PASSWORD_ARGON2ID = 3;
const PASSWORD_ARGON2_DEFAULT_MEMORY_COST = 1024;
const PASSWORD_ARGON2_DEFAULT_THREADS = 2;
const PASSWORD_ARGON2_DEFAULT_TIME_COST = 2;

