CREATE TABLE external_user (
  -- Foreign key to user_id
  eu_local_id			BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1),

  -- Some opaque identifier provided by the external database
  eu_external_id		VARCHAR(255) NOT NULL
);
