<?php

use MediaWiki\Shell\Shell;
use MediaWiki\Tests\Common\Parser\ParserTestRunner;

/**
 * The tests here verify that the PHPUnit config file covers all of the tests under /tests/phpunit
 * @group medium
 * @coversNothing
 */
class PHPUnitConfigTest extends PHPUnit\Framework\TestCase {

	public function testConfigDirectories() {
		// realpath() also normalizes directory separator on windows for prefix compares
		$testRootDir = realpath( __DIR__ . '/..' );

		$dom = new DOMDocument();
		$dom->load( __DIR__ . '/../../../phpunit.xml.template' );
		/** @var DOMElement $suites */
		$suites = $dom->documentElement->getElementsByTagName( 'testsuites' )[0];

		$suiteInfos = [];
		/** @var DOMElement $suite */
		foreach ( $suites->getElementsByTagName( 'testsuite' ) as $suite ) {
			$generalDirs = [];
			foreach ( $suite->getElementsByTagName( 'directory' ) as $dirNode ) {
				$generalDirs[] = str_replace( 'tests/phpunit/', '', $dirNode->textContent );
			}
			$excludedDirs = [];
			foreach ( $suite->getElementsByTagName( 'exclude' ) as $dirNode ) {
				$excludedDirs[] = str_replace( 'tests/phpunit/', '', $dirNode->textContent );
			}
			$suiteInfos[$suite->getAttribute( 'name' )] = [ $generalDirs, $excludedDirs ];
		}

		$directoriesFound = scandir( $testRootDir, SCANDIR_SORT_ASCENDING );
		if ( !$directoriesFound ) {
			$this->fail( "Could not scan '$testRootDir' directory" );
		}

		$directoriesNeeded = array_values( array_diff(
			array_filter(
				$directoriesFound,
				static function ( $name ) use ( $testRootDir ) {
					return (
						$name !== '.' &&
						$name !== '..' &&
						is_dir( "$testRootDir/$name" )
					);
				}
			),
			[
				'data',
				'docs',
				'documentation',
				'gen', // these are included by filename, not directory
				'mocks',
			]
		) );

		$directoriesIncluded = [];
		foreach ( $directoriesNeeded as $directory ) {
			if ( $this->isDirectoryIncluded( $directory, $suiteInfos ) ) {
				$directoriesIncluded[] = $directory;
			}
		}

		$this->assertSame(
			$directoriesNeeded,
			$directoriesIncluded,
			"All suites included"
		);
	}

	private function isDirectoryIncluded( $dir, array $suiteInfos ) {
		foreach ( $suiteInfos as [ $generalDirs, $excludedDirs ] ) {
			$found = false;
			foreach ( $generalDirs as $generalDir ) {
				if ( $this->isSameOrChildOfDirectory( $dir, $generalDir ) ) {
					$found = true;
					break;
				}
			}
			foreach ( $excludedDirs as $excludedDir ) {
				if ( $this->isSameOrChildOfDirectory( $dir, $excludedDir ) ) {
					$found = false;
					break;
				}
			}
			if ( $found ) {
				return true;
			}
		}

		return false;
	}

	private function isSameOrChildOfDirectory( $dirA, $dirB ) {
		return $dirA === $dirB || str_starts_with( "$dirB/", $dirA );
	}

	/**
	 * Verify that there is a <file> entry in the phpunit.xml config for
	 * every parser test in tests/parser/*.txt (both in core and extensions).
	 */
	public function testConfigParserTests() {
		$testRootDir = realpath( __DIR__ . '/..' );

		$dom = new DOMDocument();
		$dom->load( __DIR__ . '/../../../phpunit.xml' );
		$suites = $dom->documentElement->getElementsByTagName( 'testsuites' )[0];
		/** @var DOMElement $suite */

		// Enumerate all the <file> entries in phpunit.xml
		$filesFromConfig = [];
		foreach ( $suites->getElementsByTagName( 'testsuite' ) as $suite ) {
			foreach ( $suite->getElementsByTagName( 'file' ) as $fileNode )	{
				$contents = file_get_contents( $fileNode->textContent );
				if (
					str_contains( $contents, 'use ParserTestFileTrait;' ) &&
					preg_match( '/\$filename\s*=\s*([\'"])([^\'"]+)\1/', $contents, $matches )
				) {
					$filesFromConfig[] = stripcslashes( $matches[2] );
				}
			}
		}

		// Enumerate all the tests in tests/parser/*.txt
		$filesFromDirs = ParserTestRunner::getParserTestFiles();
		$this->assertEqualsCanonicalizing( $filesFromDirs, $filesFromConfig );
	}

	/**
	 * Test to verify that a local phpunit.xml config exists, and it matches the autogenerated file based on available
	 * extensions.
	 */
	public function testConfigUpToDate() {
		$this->markTestSkipped(
			'Causing problems with phpunit parallel runs - we should not move `phpunit.xml` out of the way - T419107'
		);
		$localCfgPath = __DIR__ . '/../../../phpunit.xml';
		$instructions = 'Generate it manually by running `composer phpunit:config`, or ' .
			'automatically by running tests via `composer phpunit`.';
		// The file should be guaranteed to exist thanks to the check in bootstrap.php, but double-check that.
		$this->assertFileExists( $localCfgPath, "No local PHPUnit config found. $instructions" );

		// Temporarily move the config out of the way to run the test. Obviously we could modify the script, e.g. by
		// adding an option to print to stdout instead of the cfg file, but that seems unnecessary for the time being.
		$tmpPath = $localCfgPath . '-tmp_move';
		rename( $localCfgPath, $tmpPath );

		try {
			// Run this in a child process to avoid any possible side effects.
			$res = Shell::command( [ PHP_BINARY, __DIR__ . '/../generatePHPUnitConfig.php' ] )->execute();
			if ( $res->getExitCode() !== 0 ) {
				$this->fail( "Cannot generate PHPUnit config. Stderr:\n" . $res->getStderr() );
			}
			$this->assertXmlFileEqualsXmlFile(
				// Note, $localCfgPath now points to the config we just generated.
				$localCfgPath,
				$tmpPath,
				"PHPUnit config is not up-to-date. $instructions"
			);
		} finally {
			rename( $tmpPath, $localCfgPath );
		}
	}
}
