-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: tests/phpunit/data/schema-maintenance/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/actor (
  actor_id BIGINT UNSIGNED NOT NULL,
  actor_user INT UNSIGNED NOT NULL,
  actor_name VARCHAR(255) NOT NULL,
  UNIQUE INDEX actor_user (actor_user),
  UNIQUE INDEX actor_name (actor_name),
  PRIMARY KEY(actor_id)
) /*$wgDBTableOptions*/;
