<?php

namespace MediaWiki\Hook;

/**
 * @stable for implementation
 * @ingroup Hooks
 */
interface AfterParserFetchFileAndTitleHook {
	/**
	 * After an image gallery is formed by Parser,
	 * just before adding its HTML to parser output.
	 *
	 * @since 1.35
	 *
	 * @param ?mixed $parser Parser object that called the hook
	 * @param ?mixed $ig Gallery, an object of one of the gallery classes (inheriting from
	 *   ImageGalleryBase)
	 * @param ?mixed &$html HTML generated by the gallery
	 * @return bool|void True or no return value to continue or false to abort
	 */
	public function onAfterParserFetchFileAndTitle( $parser, $ig, &$html );
}
