-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-templatelinks-drop-tl_title.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP INDEX tl_namespace;

DROP INDEX tl_backlinks_namespace;

ALTER TABLE templatelinks
  DROP tl_namespace;

ALTER TABLE templatelinks
  DROP tl_title;
