#!/usr/bin/env php
<?php

require( dirname( __FILE__ ) . '/../commandLine.inc' );
require 'PHPUnit/TextUI/Command.php';
define( 'MW_PHPUNIT_TEST', 1 );

$wgLocaltimezone = 'UTC';

/* Tests were failing with sqlite */
global $wgCaches;
$wgCaches[CACHE_DB] = false;

if ( !version_compare( PHPUnit_Runner_Version::id(), "3.4.1", ">" ) ) {
	echo <<<EOF
************************************************************

These tests run best with version PHPUnit 3.4.2 or later.
Earlier versions may show failures because earlier versions
of PHPUnit do not properly implement dependencies.

************************************************************

EOF;
}

$command = new PHPUnit_TextUI_Command;
$command->run( $argv );

