#!/usr/bin/env php
<?php

/**
 * This script generates a phpunit.xml file that can be used to run PHPUnit on both MW core and every
 * installed extension and skin. It works by reading a list of extensions and skins from the settings files,
 * and then adding everything it finds to a new phpunit.xml file, which is excluded from version control.
 * The config file is based on phpunit.xml.dist (included in version control).
 */

use MediaWiki\HookContainer\HookRunner;
use MediaWiki\MediaWikiServices;
use PHPUnit\Util\Xml\Loader as XmlLoader;

require_once __DIR__ . '/../../vendor/autoload.php';
require_once __DIR__ . '/bootstrap.common.php';

echo "Generating PHPUnit config\n";

TestSetup::loadSettingsFiles();

$extensionsAndSkinPaths = array_map( 'dirname', array_keys( ExtensionRegistry::getInstance()->getQueue() ) );
// Build a list of extension tests, based on autodiscovered tests as well as tests added with the
// UnitTestsList hook.
$rawTestPaths = [];
$extRegistry = ExtensionRegistry::getInstance();
foreach ( $extRegistry->getAllThings() as $extInfo ) {
	$rawTestPaths[] = dirname( $extInfo['path'] ) . '/tests/phpunit';
}
// Extensions can return a list of files or directories
( new HookRunner( MediaWikiServices::getInstance()->getHookContainer() ) )->onUnitTestsList( $rawTestPaths );
$rawTestPaths = array_unique( $rawTestPaths );

// Note: unit tests make no distinction between extensions and skins.
$extUnitTestPaths = [];
foreach ( $extensionsAndSkinPaths as $componentPath ) {
	$extUnitTestPaths[] = "$componentPath/tests/phpunit/unit";
}

$extTestPaths = [];
$skinTestPaths = [];
foreach ( $rawTestPaths as $path ) {
	if ( str_contains( strtr( $path, '\\', '/' ), '/extensions/' ) ) {
		$extTestPaths[] = $path;
	} else {
		$skinTestPaths[] = $path;
	}
}

$baseConfigPath = __DIR__ . '/../../phpunit.xml.dist';
$outConfigPath = __DIR__ . '/../../phpunit.xml';

$config = ( new XmlLoader )->loadFile( $baseConfigPath, false, true, true );
$xpath = new DOMXPath( $config );

$warning = $config->createComment(
	"\nThis file is generated by tests/phpunit/generatePHPUnitConfig.php. Any changes you make will be lost\n" .
	"upon running the script. This file is also excluded from version control.\n"
);
$config->insertBefore( $warning, $config->firstChild );

$addNodeFromPath = static function ( DOMNode $parent, string $path ) use ( $config ): void {
	if ( is_dir( $path ) ) {
		$nodeType = 'directory';
	} elseif ( is_file( $path ) ) {
		$nodeType = 'file';
	} else {
		// Doesn't exist. Skip.
		return;
	}
	$node = $config->createElement( $nodeType, $path );
	$parent->appendChild( $node );
};

$extensionsSuite = $xpath->query( '//testsuite[@name="extensions"]' )->item( 0 );
foreach ( $extTestPaths as $extPath ) {
	$addNodeFromPath( $extensionsSuite, $extPath );
}

$skinsSuite = $xpath->query( '//testsuite[@name="skins"]' )->item( 0 );
foreach ( $skinTestPaths as $skinPath ) {
	$addNodeFromPath( $skinsSuite, $skinPath );
}

$extensionsUnitSuite = $xpath->query( '//testsuite[@name="extensions:unit"]' )->item( 0 );
foreach ( $extUnitTestPaths as $extUnitPath ) {
	$addNodeFromPath( $extensionsUnitSuite, $extUnitPath );
}

$config->formatOutput = true;
file_put_contents( $outConfigPath, $config->saveXML() );

echo "Config written to " . realpath( $outConfigPath ) . "\n";
