<?php

/* This defines autoloading handler for whole MediaWiki framework */

ini_set('unserialize_callback_func', '__autoload' );

class AutoLoader {
	# Locations of core classes
	# Extension classes are specified with $wgAutoloadClasses
	static $localClasses = array(
		# Includes
		'AjaxDispatcher' => 'includes/AjaxDispatcher.php',
		'AjaxResponse' => 'includes/AjaxResponse.php',
		'AlphabeticPager' => 'includes/Pager.php',
		'APCBagOStuff' => 'includes/BagOStuff.php',
		'ArrayDiffFormatter' => 'includes/DifferenceEngine.php',
		'Article' => 'includes/Article.php',
		'AtomFeed' => 'includes/Feed.php',
		'AuthPlugin' => 'includes/AuthPlugin.php',
		'Autopromote' => 'includes/Autopromote.php',
		'BagOStuff' => 'includes/BagOStuff.php',
		'Block' => 'includes/Block.php',
		'CacheDependency' => 'includes/CacheDependency.php',
		'Category' => 'includes/Category.php',
		'Categoryfinder' => 'includes/Categoryfinder.php',
		'CategoryPage' => 'includes/CategoryPage.php',
		'CategoryViewer' => 'includes/CategoryPage.php',
		'ChangesList' => 'includes/ChangesList.php',
		'ChangesFeed' => 'includes/ChangesFeed.php',
		'ChannelFeed' => 'includes/Feed.php',
		'ConcatenatedGzipHistoryBlob' => 'includes/HistoryBlob.php',
		'ConstantDependency' => 'includes/CacheDependency.php',
		'DBABagOStuff' => 'includes/BagOStuff.php',
		'DependencyWrapper' => 'includes/CacheDependency.php',
		'_DiffEngine' => 'includes/DifferenceEngine.php',
		'DifferenceEngine' => 'includes/DifferenceEngine.php',
		'DiffFormatter' => 'includes/DifferenceEngine.php',
		'Diff' => 'includes/DifferenceEngine.php',
		'_DiffOp_Add' => 'includes/DifferenceEngine.php',
		'_DiffOp_Change' => 'includes/DifferenceEngine.php',
		'_DiffOp_Copy' => 'includes/DifferenceEngine.php',
		'_DiffOp_Delete' => 'includes/DifferenceEngine.php',
		'_DiffOp' => 'includes/DifferenceEngine.php',
		'DjVuImage' => 'includes/DjVuImage.php',
		'DoubleReplacer' => 'includes/StringUtils.php',
		'Dump7ZipOutput' => 'includes/Export.php',
		'DumpBZip2Output' => 'includes/Export.php',
		'DumpFileOutput' => 'includes/Export.php',
		'DumpFilter' => 'includes/Export.php',
		'DumpGZipOutput' => 'includes/Export.php',
		'DumpLatestFilter' => 'includes/Export.php',
		'DumpMultiWriter' => 'includes/Export.php',
		'DumpNamespaceFilter' => 'includes/Export.php',
		'DumpNotalkFilter' => 'includes/Export.php',
		'DumpOutput' => 'includes/Export.php',
		'DumpPipeOutput' => 'includes/Export.php',
		'eAccelBagOStuff' => 'includes/BagOStuff.php',
		'EditPage' => 'includes/EditPage.php',
		'EmaillingJob' => 'includes/EmaillingJob.php',
		'EmailNotification' => 'includes/UserMailer.php',
		'EnhancedChangesList' => 'includes/ChangesList.php',
		'EnotifNotifyJob' => 'includes/EnotifNotifyJob.php',
		'ErrorPageError' => 'includes/Exception.php',
		'Exif' => 'includes/Exif.php',
		'ExternalEdit' => 'includes/ExternalEdit.php',
		'ExternalStoreDB' => 'includes/ExternalStoreDB.php',
		'ExternalStoreHttp' => 'includes/ExternalStoreHttp.php',
		'ExternalStore' => 'includes/ExternalStore.php',
		'FatalError' => 'includes/Exception.php',
		'FakeTitle' => 'includes/FakeTitle.php',
		'FauxRequest' => 'includes/WebRequest.php',
		'FeedItem' => 'includes/Feed.php',
		'FeedUtils' => 'includes/FeedUtils.php',
		'FileDeleteForm' => 'includes/FileDeleteForm.php',
		'FileDependency' => 'includes/CacheDependency.php',
		'FileRevertForm' => 'includes/FileRevertForm.php',
		'FileStore' => 'includes/FileStore.php',
		'FormatExif' => 'includes/Exif.php',
		'FormOptions' => 'includes/FormOptions.php',
		'FSException' => 'includes/FileStore.php',
		'FSTransaction' => 'includes/FileStore.php',
		'GlobalDependency' => 'includes/CacheDependency.php',
		'HashBagOStuff' => 'includes/BagOStuff.php',
		'HashtableReplacer' => 'includes/StringUtils.php',
		'HistoryBlobCurStub' => 'includes/HistoryBlob.php',
		'HistoryBlob' => 'includes/HistoryBlob.php',
		'HistoryBlobStub' => 'includes/HistoryBlob.php',
		'HTMLCacheUpdate' => 'includes/HTMLCacheUpdate.php',
		'HTMLCacheUpdateJob' => 'includes/HTMLCacheUpdate.php',
		'HTMLFileCache' => 'includes/HTMLFileCache.php',
		'Http' => 'includes/HttpFunctions.php',
		'_HWLDF_WordAccumulator' => 'includes/DifferenceEngine.php',
		'ImageGallery' => 'includes/ImageGallery.php',
		'ImageHistoryList' => 'includes/ImagePage.php',
		'ImagePage' => 'includes/ImagePage.php',
		'ImageQueryPage' => 'includes/ImageQueryPage.php',
		'IncludableSpecialPage' => 'includes/SpecialPage.php',
		'IndexPager' => 'includes/Pager.php',
		'IP' => 'includes/IP.php',
		'Job' => 'includes/JobQueue.php',
		'License' => 'includes/Licenses.php',
		'Licenses' => 'includes/Licenses.php',
		'LinkBatch' => 'includes/LinkBatch.php',
		'LinkCache' => 'includes/LinkCache.php',
		'Linker' => 'includes/Linker.php',
		'LinkFilter' => 'includes/LinkFilter.php',
		'LinksUpdate' => 'includes/LinksUpdate.php',
		'LogPage' => 'includes/LogPage.php',
		'LogPager' => 'includes/LogEventsList.php',
		'LogEventsList' => 'includes/LogEventsList.php',
		'LogReader' => 'includes/LogEventsList.php',
		'LogViewer' => 'includes/LogEventsList.php',
		'MacBinary' => 'includes/MacBinary.php',
		'MagicWordArray' => 'includes/MagicWord.php',
		'MagicWord' => 'includes/MagicWord.php',
		'MailAddress' => 'includes/UserMailer.php',
		'MappedDiff' => 'includes/DifferenceEngine.php',
		'MathRenderer' => 'includes/Math.php',
		'MediaTransformError' => 'includes/MediaTransformOutput.php',
		'MediaTransformOutput' => 'includes/MediaTransformOutput.php',
		'MediaWikiBagOStuff' => 'includes/BagOStuff.php',
		'MediaWiki_I18N' => 'includes/SkinTemplate.php',
		'MediaWiki' => 'includes/Wiki.php',
		'memcached' => 'includes/memcached-client.php',
		'MessageCache' => 'includes/MessageCache.php',
		'MimeMagic' => 'includes/MimeMagic.php',
		'MWException' => 'includes/Exception.php',
		'MWNamespace' => 'includes/Namespace.php',
		'Namespace' => 'includes/NamespaceCompat.php', // Compat
		'OldChangesList' => 'includes/ChangesList.php',
		'OutputPage' => 'includes/OutputPage.php',
		'PageHistory' => 'includes/PageHistory.php',
		'PageHistoryPager' => 'includes/PageHistory.php',
		'PageQueryPage' => 'includes/PageQueryPage.php',
		'Pager' => 'includes/Pager.php',
		'PasswordError' => 'includes/User.php',
		'PatrolLog' => 'includes/PatrolLog.php',
		'PrefixSearch' => 'includes/PrefixSearch.php',
		'Profiler' => 'includes/Profiler.php',
		'ProfilerSimple' => 'includes/ProfilerSimple.php',
		'ProfilerSimpleText' => 'includes/ProfilerSimpleText.php',
		'ProfilerSimpleUDP' => 'includes/ProfilerSimpleUDP.php',
		'ProtectionForm' => 'includes/ProtectionForm.php',
		'QueryPage' => 'includes/QueryPage.php',
		'QuickTemplate' => 'includes/SkinTemplate.php',
		'RawPage' => 'includes/RawPage.php',
		'RCCacheEntry' => 'includes/ChangesList.php',
		'RecentChange' => 'includes/RecentChange.php',
		'RefreshLinksJob' => 'includes/RefreshLinksJob.php',
		'RegexlikeReplacer' => 'includes/StringUtils.php',
		'ReplacementArray' => 'includes/StringUtils.php',
		'Replacer' => 'includes/StringUtils.php',
		'ReverseChronologicalPager' => 'includes/Pager.php',
		'Revision' => 'includes/Revision.php',
		'RSSFeed' => 'includes/Feed.php',
		'Sanitizer' => 'includes/Sanitizer.php',
		'SiteConfiguration' => 'includes/SiteConfiguration.php',
		'SiteStats' => 'includes/SiteStats.php',
		'SiteStatsUpdate' => 'includes/SiteStats.php',
		'Skin' => 'includes/Skin.php',
		'SkinTemplate' => 'includes/SkinTemplate.php',
		'SpecialMycontributions' => 'includes/SpecialPage.php',
		'SpecialMypage' => 'includes/SpecialPage.php',
		'SpecialMytalk' => 'includes/SpecialPage.php',
		'SpecialPage' => 'includes/SpecialPage.php',
		'SpecialRedirectToSpecial' => 'includes/SpecialPage.php',
		'SqlBagOStuff' => 'includes/BagOStuff.php',
		'SquidUpdate' => 'includes/SquidUpdate.php',
		'Status' => 'includes/Status.php',
		'StringUtils' => 'includes/StringUtils.php',
		'TableDiffFormatter' => 'includes/DifferenceEngine.php',
		'TablePager' => 'includes/Pager.php',
		'ThumbnailImage' => 'includes/MediaTransformOutput.php',
		'TitleDependency' => 'includes/CacheDependency.php',
		'Title' => 'includes/Title.php',
		'TitleListDependency' => 'includes/CacheDependency.php',
		'TransformParameterError' => 'includes/MediaTransformOutput.php',
		'TurckBagOStuff' => 'includes/BagOStuff.php',
		'UnifiedDiffFormatter' => 'includes/DifferenceEngine.php',
		'UnlistedSpecialPage' => 'includes/SpecialPage.php',
		'User' => 'includes/User.php',
		'UserArray' => 'includes/UserArray.php',
		'UserArrayFromResult' => 'includes/UserArray.php',
		'UserMailer' => 'includes/UserMailer.php',
		'UserRightsProxy' => 'includes/UserRightsProxy.php',
		'WatchedItem' => 'includes/WatchedItem.php',
		'WatchlistEditor' => 'includes/WatchlistEditor.php',
		'WebRequest' => 'includes/WebRequest.php',
		'WebResponse' => 'includes/WebResponse.php',
		'WikiError' => 'includes/WikiError.php',
		'WikiErrorMsg' => 'includes/WikiError.php',
		'WikiExporter' => 'includes/Export.php',
		'WikiXmlError' => 'includes/WikiError.php',
		'WordLevelDiff' => 'includes/DifferenceEngine.php',
		'XCacheBagOStuff' => 'includes/BagOStuff.php',
		'XmlDumpWriter' => 'includes/Export.php',
		'Xml' => 'includes/Xml.php',
		'XmlSelect' => 'includes/Xml.php',
		'XmlTypeCheck' => 'includes/XmlTypeCheck.php',
		'ZhClient' => 'includes/ZhClient.php',

		# includes/api
		'ApiBase' => 'includes/api/ApiBase.php',
		'ApiBlock' => 'includes/api/ApiBlock.php',
		'ApiDelete' => 'includes/api/ApiDelete.php',
		'ApiEditPage' => 'includes/api/ApiEditPage.php',
		'ApiEmailUser' => 'includes/api/ApiEmailUser.php',
		'ApiExpandTemplates' => 'includes/api/ApiExpandTemplates.php',
		'ApiFeedWatchlist' => 'includes/api/ApiFeedWatchlist.php',
		'ApiFormatBase' => 'includes/api/ApiFormatBase.php',
		'ApiFormatDbg' => 'includes/api/ApiFormatDbg.php',
		'ApiFormatFeedWrapper' => 'includes/api/ApiFormatBase.php',
		'ApiFormatJson' => 'includes/api/ApiFormatJson.php',
		'ApiFormatPhp' => 'includes/api/ApiFormatPhp.php',
		'ApiFormatTxt' => 'includes/api/ApiFormatTxt.php',
		'ApiFormatWddx' => 'includes/api/ApiFormatWddx.php',
		'ApiFormatXml' => 'includes/api/ApiFormatXml.php',
		'ApiFormatYaml' => 'includes/api/ApiFormatYaml.php',
		'ApiHelp' => 'includes/api/ApiHelp.php',
		'ApiLogin' => 'includes/api/ApiLogin.php',
		'ApiLogout' => 'includes/api/ApiLogout.php',
		'ApiMain' => 'includes/api/ApiMain.php',
		'ApiMove' => 'includes/api/ApiMove.php',
		'ApiOpenSearch' => 'includes/api/ApiOpenSearch.php',
		'ApiPageSet' => 'includes/api/ApiPageSet.php',
		'ApiParamInfo' => 'includes/api/ApiParamInfo.php',
		'ApiParse' => 'includes/api/ApiParse.php',
		'ApiProtect' => 'includes/api/ApiProtect.php',
		'ApiQuery' => 'includes/api/ApiQuery.php',
		'ApiQueryAllCategories' => 'includes/api/ApiQueryAllCategories.php',
		'ApiQueryAllimages' => 'includes/api/ApiQueryAllimages.php',
		'ApiQueryAllLinks' => 'includes/api/ApiQueryAllLinks.php',
		'ApiQueryAllUsers' => 'includes/api/ApiQueryAllUsers.php',
		'ApiQueryAllmessages' => 'includes/api/ApiQueryAllmessages.php',
		'ApiQueryAllpages' => 'includes/api/ApiQueryAllpages.php',
		'ApiQueryBacklinks' => 'includes/api/ApiQueryBacklinks.php',
		'ApiQueryBase' => 'includes/api/ApiQueryBase.php',
		'ApiQueryBlocks' => 'includes/api/ApiQueryBlocks.php',
		'ApiQueryCategories' => 'includes/api/ApiQueryCategories.php',
		'ApiQueryCategoryInfo' => 'includes/api/ApiQueryCategoryInfo.php',
		'ApiQueryCategoryMembers' => 'includes/api/ApiQueryCategoryMembers.php',
		'ApiQueryContributions' => 'includes/api/ApiQueryUserContributions.php',
		'ApiQueryDeletedrevs' => 'includes/api/ApiQueryDeletedrevs.php',
		'ApiQueryExtLinksUsage' => 'includes/api/ApiQueryExtLinksUsage.php',
		'ApiQueryExternalLinks' => 'includes/api/ApiQueryExternalLinks.php',
		'ApiQueryGeneratorBase' => 'includes/api/ApiQueryBase.php',
		'ApiQueryImageInfo' => 'includes/api/ApiQueryImageInfo.php',
		'ApiQueryImages' => 'includes/api/ApiQueryImages.php',
		'ApiQueryInfo' => 'includes/api/ApiQueryInfo.php',
		'ApiQueryLangLinks' => 'includes/api/ApiQueryLangLinks.php',
		'ApiQueryLinks' => 'includes/api/ApiQueryLinks.php',
		'ApiQueryLogEvents' => 'includes/api/ApiQueryLogEvents.php',
		'ApiQueryRandom' => 'includes/api/ApiQueryRandom.php',
		'ApiQueryRecentChanges'=> 'includes/api/ApiQueryRecentChanges.php',
		'ApiQueryRevisions' => 'includes/api/ApiQueryRevisions.php',
		'ApiQuerySearch' => 'includes/api/ApiQuerySearch.php',
		'ApiQuerySiteinfo' => 'includes/api/ApiQuerySiteinfo.php',
		'ApiQueryUserInfo' => 'includes/api/ApiQueryUserInfo.php',
		'ApiQueryUsers' => 'includes/api/ApiQueryUsers.php',
		'ApiQueryWatchlist' => 'includes/api/ApiQueryWatchlist.php',
		'ApiResult' => 'includes/api/ApiResult.php',
		'ApiRollback' => 'includes/api/ApiRollback.php',
		'ApiUnblock' => 'includes/api/ApiUnblock.php',
		'ApiUndelete' => 'includes/api/ApiUndelete.php',
		'Services_JSON' => 'includes/api/ApiFormatJson_json.php',
		'Services_JSON_Error' => 'includes/api/ApiFormatJson_json.php',
		'Spyc' => 'includes/api/ApiFormatYaml_spyc.php',
		'UsageException' => 'includes/api/ApiMain.php',
		'YAMLNode' => 'includes/api/ApiFormatYaml_spyc.php',

		# includes/db
		'Blob' => 'includes/db/Database.php',
		'ChronologyProtector' => 'includes/db/LBFactory.php',
		'Database' => 'includes/db/Database.php',
		'DatabaseMssql' => 'includes/db/DatabaseMssql.php',
		'DatabaseMysql' => 'includes/db/Database.php',
		'DatabaseOracle' => 'includes/db/DatabaseOracle.php',
		'DatabasePostgres' => 'includes/db/DatabasePostgres.php',
		'DatabaseSqlite' => 'includes/db/DatabaseSqlite.php',
		'DBConnectionError' => 'includes/db/Database.php',
		'DBError' => 'includes/db/Database.php',
		'DBObject' => 'includes/db/Database.php',
		'DBQueryError' => 'includes/db/Database.php',
		'DBUnexpectedError' => 'includes/db/Database.php',
		'LBFactory' => 'includes/db/LBFactory.php',
		'LBFactory_Multi' => 'includes/db/LBFactory_Multi.php',
		'LBFactory_Simple' => 'includes/db/LBFactory.php',
		'LoadBalancer' => 'includes/db/LoadBalancer.php',
		'MSSQLField' => 'includes/db/DatabaseMssql.php',
		'MySQLField' => 'includes/db/Database.php',
		'MySQLMasterPos' => 'includes/db/Database.php',
		'ORABlob' => 'includes/db/DatabaseOracle.php',
		'ORAResult' => 'includes/db/DatabaseOracle.php',
		'PostgresField' => 'includes/db/DatabasePostgres.php',
		'ResultWrapper' => 'includes/db/Database.php',
		'SQLiteField' => 'includes/db/DatabaseSqlite.php',

		# includes/filerepo
		'ArchivedFile' => 'includes/filerepo/ArchivedFile.php',
		'File' => 'includes/filerepo/File.php',
		'FileRepo' => 'includes/filerepo/FileRepo.php',
		'FileRepoStatus' => 'includes/filerepo/FileRepoStatus.php',
		'ForeignAPIFile' => 'includes/filerepo/ForeignAPIFile.php',
		'ForeignAPIRepo' => 'includes/filerepo/ForeignAPIRepo.php',
		'ForeignDBFile' => 'includes/filerepo/ForeignDBFile.php',
		'ForeignDBRepo' => 'includes/filerepo/ForeignDBRepo.php',
		'ForeignDBViaLBRepo' => 'includes/filerepo/ForeignDBViaLBRepo.php',
		'FSRepo' => 'includes/filerepo/FSRepo.php',
		'Image' => 'includes/filerepo/Image.php',
		'LocalFile' => 'includes/filerepo/LocalFile.php',
		'LocalFileDeleteBatch' => 'includes/filerepo/LocalFile.php',
		'LocalFileMoveBatch' => 'includes/filerepo/LocalFile.php',
		'LocalFileRestoreBatch' => 'includes/filerepo/LocalFile.php',
		'LocalRepo' => 'includes/filerepo/LocalRepo.php',
		'OldLocalFile' => 'includes/filerepo/OldLocalFile.php',
		'RepoGroup' => 'includes/filerepo/RepoGroup.php',
		'UnregisteredLocalFile' => 'includes/filerepo/UnregisteredLocalFile.php',

		# includes/media
		'BitmapHandler' => 'includes/media/Bitmap.php',
		'BmpHandler' => 'includes/media/BMP.php',
		'DjVuHandler' => 'includes/media/DjVu.php',
		'ImageHandler' => 'includes/media/Generic.php',
		'MediaHandler' => 'includes/media/Generic.php',
		'SvgHandler' => 'includes/media/SVG.php',

		# includes/normal
		'UtfNormal' => 'includes/normal/UtfNormal.php',

		# includes/parser
		'CoreParserFunctions' => 'includes/parser/CoreParserFunctions.php',
		'DateFormatter' => 'includes/parser/DateFormatter.php',
		'OnlyIncludeReplacer' => 'includes/parser/Parser.php',
		'PPDAccum_Hash' => 'includes/parser/Preprocessor_Hash.php',
		'PPDPart' => 'includes/parser/Preprocessor_DOM.php',
		'PPDPart_Hash' => 'includes/parser/Preprocessor_Hash.php',
		'PPDStack' => 'includes/parser/Preprocessor_DOM.php',
		'PPDStackElement' => 'includes/parser/Preprocessor_DOM.php',
		'PPDStackElement_Hash' => 'includes/parser/Preprocessor_Hash.php',
		'PPDStack_Hash' => 'includes/parser/Preprocessor_Hash.php',
		'PPFrame' => 'includes/parser/Preprocessor.php',
		'PPFrame_DOM' => 'includes/parser/Preprocessor_DOM.php',
		'PPFrame_Hash' => 'includes/parser/Preprocessor_Hash.php',
		'PPNode' => 'includes/parser/Preprocessor.php',
		'PPNode_DOM' => 'includes/parser/Preprocessor_DOM.php',
		'PPNode_Hash_Array' => 'includes/parser/Preprocessor_Hash.php',
		'PPNode_Hash_Attr' => 'includes/parser/Preprocessor_Hash.php',
		'PPNode_Hash_Text' => 'includes/parser/Preprocessor_Hash.php',
		'PPNode_Hash_Tree' => 'includes/parser/Preprocessor_Hash.php',
		'PPTemplateFrame_DOM' => 'includes/parser/Preprocessor_DOM.php',
		'PPTemplateFrame_Hash' => 'includes/parser/Preprocessor_Hash.php',
		'Parser' => 'includes/parser/Parser.php',
		'ParserCache' => 'includes/parser/ParserCache.php',
		'ParserOptions' => 'includes/parser/ParserOptions.php',
		'ParserOutput' => 'includes/parser/ParserOutput.php',
		'Parser_DiffTest' => 'includes/parser/Parser_DiffTest.php',
		'Parser_OldPP' => 'includes/parser/Parser_OldPP.php',
		'Preprocessor' => 'includes/parser/Preprocessor.php',
		'Preprocessor_DOM' => 'includes/parser/Preprocessor_DOM.php',
		'Preprocessor_Hash' => 'includes/parser/Preprocessor_Hash.php',
		'StripState' => 'includes/parser/Parser.php',

		# includes/search
		'OracleSearchResultSet' => 'includes/search/Oracle.php',
		'PostgresSearchResult' => 'includes/search/Postgres.php',
		'PostgresSearchResultSet' => 'includes/search/Postgres.php',		
		'MySQLSearchResultSet' => 'includes/Search/MySQL.php',
		'SearchEngineDummy' => 'includes/search/Engine.php',
		'SearchEngine' => 'includes/search/Engine.php',
		'SearchHighlighter' => 'includes/search/Engine.php',
		'SearchMySQL4' => 'includes/search/MySQL4.php',
		'SearchMySQL' => 'includes/search/MySQL.php',
		'SearchOracle' => 'includes/search/Oracle.php',
		'SearchPostgres' => 'includes/search/Postgres.php',
		'SearchResult' => 'includes/search/Engine.php',
		'SearchResultSet' => 'includes/search/Engine.php',
		'SearchResultTooMany' => 'includes/search/Engine.php',
		'SearchUpdate' => 'includes/search/Update.php',
		'SearchUpdateMyISAM' => 'includes/search/Update.php',
		
		# includes/specials
		'AncientPagesPage' => 'includes/specials/Ancientpages.php',
		'BrokenRedirectsPage' => 'includes/specials/BrokenRedirects.php',
		'ContribsPager' => 'includes/specials/Contributions.php',
		'DBLockForm' => 'includes/specials/Lockdb.php',
		'DBUnlockForm' => 'includes/specials/Unlockdb.php',
		'DeadendPagesPage' => 'includes/specials/Deadendpages.php',
		'DisambiguationsPage' => 'includes/specials/Disambiguations.php',
		'DoubleRedirectsPage' => 'includes/specials/DoubleRedirects.php',
		'EmailConfirmation' => 'includes/specials/Confirmemail.php',
		'EmailInvalidation' => 'includes/specials/Confirmemail.php',
		'EmailUserForm' => 'includes/specials/Emailuser.php',
		'FewestrevisionsPage' => 'includes/specials/Fewestrevisions.php',
		'FileDuplicateSearchPage' => 'includes/specials/FileDuplicateSearch.php',
		'IPBlockForm' => 'includes/specials/Blockip.php',
		'IPBlocklistPager' => 'includes/specials/Ipblocklist.php',
		'IPUnblockForm' => 'includes/specials/Ipblocklist.php',
		'ImportReporter' => 'includes/specials/Import.php',
		'ImportStreamSource' => 'includes/specials/Import.php',
		'ImportStringSource' => 'includes/specials/Import.php',
		'ListredirectsPage' => 'includes/specials/Listredirects.php',
		'LoginForm' => 'includes/specials/Userlogin.php',
		'LonelyPagesPage' => 'includes/specials/Lonelypages.php',
		'LongPagesPage' => 'includes/specials/Longpages.php',
		'MIMEsearchPage' => 'includes/specials/MIMEsearch.php',
		'MostcategoriesPage' => 'includes/specials/Mostcategories.php',
		'MostimagesPage' => 'includes/specials/Mostimages.php',
		'MostlinkedCategoriesPage' => 'includes/specials/Mostlinkedcategories.php',
		'MostlinkedPage' => 'includes/specials/Mostlinked.php',
		'MostrevisionsPage' => 'includes/specials/Mostrevisions.php',
		'MovePageForm' => 'includes/specials/Movepage.php',
		'NewPagesForm' => 'includes/specials/Newpages.php',
		'NewPagesPager' => 'includes/specials/Newpages.php',
		'PageArchive' => 'includes/specials/Undelete.php',
		'PasswordResetForm' => 'includes/specials/Resetpass.php',
		'PopularPagesPage' => 'includes/specials/Popularpages.php',
		'PreferencesForm' => 'includes/specials/Preferences.php',
		'RandomPage' => 'includes/specials/Randompage.php',
		'RevisionDeleteForm' => 'includes/specials/Revisiondelete.php',
		'RevisionDeleter' => 'includes/specials/Revisiondelete.php',
		'ShortPagesPage' => 'includes/specials/Shortpages.php',
		'SpecialAllpages' => 'includes/specials/Allpages.php',
		'SpecialBookSources' => 'includes/specials/Booksources.php',
		'SpecialListGroupRights' => 'includes/specials/Listgrouprights.php',
		'SpecialMostlinkedtemplates' => 'includes/specials/Mostlinkedtemplates.php',
		'SpecialPrefixindex' => 'includes/specials/Prefixindex.php',
		'SpecialRandomredirect' => 'includes/specials/Randomredirect.php',
		'SpecialRecentChanges' => 'includes/specials/Recentchanges.php',
		'SpecialSearch' => 'includes/specials/Search.php',
		'SpecialVersion' => 'includes/specials/Version.php',
		'UncategorizedCategoriesPage' => 'includes/specials/Uncategorizedcategories.php',
		'UncategorizedPagesPage' => 'includes/specials/Uncategorizedpages.php',
		'UncategorizedTemplatesPage' => 'includes/specials/Uncategorizedtemplates.php',
		'UndeleteForm' => 'includes/specials/Undelete.php',
		'UnusedCategoriesPage' => 'includes/specials/Unusedcategories.php',
		'UnusedimagesPage' => 'includes/specials/Unusedimages.php',
		'UnusedtemplatesPage' => 'includes/specials/Unusedtemplates.php',
		'UnwatchedpagesPage' => 'includes/specials/Unwatchedpages.php',
		'UploadForm' => 'includes/specials/Upload.php',
		'UploadFormMogile' => 'includes/specials/UploadMogile.php',
		'UserrightsPage' => 'includes/specials/Userrights.php',
		'UsersPager' => 'includes/specials/Listusers.php',
		'WantedCategoriesPage' => 'includes/specials/Wantedcategories.php',
		'WantedPagesPage' => 'includes/specials/Wantedpages.php',
		'WhatLinksHerePage' => 'includes/specials/Whatlinkshere.php',
		'WikiImporter' => 'includes/specials/Import.php',
		'WikiRevision' => 'includes/specials/Import.php',
		'WithoutInterwikiPage' => 'includes/specials/Withoutinterwiki.php',

		# includes/templates
		'UsercreateTemplate' => 'includes/templates/Userlogin.php',
		'UserloginTemplate' => 'includes/templates/Userlogin.php',

		# languages
		'Language' => 'languages/Language.php',
		'FakeConverter' => 'languages/Language.php',

	);

	static function autoload( $className ) {
		global $wgAutoloadClasses;

		wfProfileIn( __METHOD__ );
		if ( isset( self::$localClasses[$className] ) ) {
			$filename = self::$localClasses[$className];
		} elseif ( isset( $wgAutoloadClasses[$className] ) ) {
			$filename = $wgAutoloadClasses[$className];
		} else {
			# Try a different capitalisation
			# The case can sometimes be wrong when unserializing PHP 4 objects
			$filename = false;
			$lowerClass = strtolower( $className );
			foreach ( self::$localClasses as $class2 => $file2 ) {
				if ( strtolower( $class2 ) == $lowerClass ) {
					$filename = $file2;
				}
			}
			if ( !$filename ) {
				# Give up
				wfProfileOut( __METHOD__ );
				return;
			}
		}

		# Make an absolute path, this improves performance by avoiding some stat calls
		if ( substr( $filename, 0, 1 ) != '/' && substr( $filename, 1, 1 ) != ':' ) {
			global $IP;
			$filename = "$IP/$filename";
		}
		require( $filename );
		wfProfileOut( __METHOD__ );
	}

	static function loadAllExtensions() {
		global $wgAutoloadClasses;

		# It is crucial that SpecialPage.php is included before any special page
		# extensions are loaded. Otherwise the parent class will not be available
		# when APC loads the early-bound extension class. Normally this is
		# guaranteed by entering special pages via SpecialPage members such as
		# executePath(), but here we have to take a more explicit measure.

		require_once( dirname(__FILE__) . '/SpecialPage.php' );

		foreach( $wgAutoloadClasses as $class => $file ) {
			if( !( class_exists( $class ) || interface_exists( $class ) ) ) {
				require( $file );
			}
		}
	}
}

function wfLoadAllExtensions() {
	AutoLoader::loadAllExtensions();
}

if ( function_exists( 'spl_autoload_register' ) ) {
	spl_autoload_register( array( 'AutoLoader', 'autoload' ) );
} else {
	function __autoload( $class ) {
		AutoLoader::autoload( $class );
	}
}

