<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir;

return array(
    'Monolog\\' => array($vendorDir . '/monolog/monolog/src/Monolog'),
);
