-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-objectcache-drop-modtoken.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TEMPORARY TABLE /*_*/__temp__objectcache AS
SELECT
  keyname,
  value,
  exptime
FROM /*_*/objectcache;

DROP TABLE /*_*/objectcache;


CREATE TABLE /*_*/objectcache (
  keyname BLOB DEFAULT '' NOT NULL,
  value BLOB DEFAULT NULL,
  exptime BLOB NOT NULL,
  PRIMARY KEY(keyname)
);

INSERT INTO /*_*/objectcache (keyname, value, exptime)
SELECT
  keyname,
  value,
  exptime
FROM /*_*/__temp__objectcache;

DROP TABLE /*_*/__temp__objectcache;

CREATE INDEX exptime ON /*_*/objectcache (exptime);
