name: PR Documentation Check

on:
  pull_request:
    branches:
      - '**'

jobs:
  check-doc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run documentation check
        run: |
          echo "Checking PR for documentation..."
          python .github/scripts/check_docs.py
