-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-site_stats-temp_users.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE /*_*/site_stats
  ADD ss_temp_users BIGINT UNSIGNED DEFAULT NULL,
  ADD ss_active_temp_users BIGINT UNSIGNED DEFAULT NULL;
