-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: maintenance/abstractSchemaChanges/patch-ipblocks-ipb_id.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE  /*_*/ipblocks
CHANGE  ipb_id ipb_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
CHANGE  ipb_parent_block_id ipb_parent_block_id INT UNSIGNED DEFAULT NULL;